### ISSUE TITLE
Auto-play at the final episode.

### ISSUE THREAD

**Issue by DavidBonsant** [thedrummeraki/tanoshimu#28]
The autoplay got me from the last epoisode of kokoro connect to this episode:
https://tanoshimu.herokuapp.com/shows/episodes?id=1123

**Comment by thedrummeraki** [comment]
Yep, looks very weird. It does redirect to that episode, instead of https://tanoshimu.herokuapp.com/shows.

I will look into at home

**Comment by thedrummeraki** [comment]
Fixed #28 with commit f497ad7.
